<?

$var = 

<<<EOD
Lolita, light of my life, fire of my loins. My sin, my soul. Lo-lee-ta: the tip of the tongue taking a trip of three steps down the palate to tap, at three, on the teeth. Lo. Lee. Ta.
She was Lo, plain Lo, in the morning, standing four feet ten in one sock. She was Lola in slacks. She was Dolly at school. She was Dolores on the dotted line. But in my arms she was always Lolita.

Did she have a precursor? She did, indeed she did. In point of fact, there might have been no Lolita at all had I not loved, one summer, a certain initial girl-child. In a princedom by the sea. Oh when? About as many years before Lolita was born as my age was that summer. You can always count on a murderer for a fancy prose style.

Ladies and gentlemen of the jury, exhibit number one is what the seraphs, the misinformed, simple, noble-winged seraphs, envied. Look at this tangle of thorns.

I was born in 1910, in Paris. My father was a gentle, easy-going person, a salad of racial genes: a Swiss citizen, of mixed French and Austrian descent, with a dash of the Danube in his veins. I am going to pass around in a minute some lovely, glossy-blue picture-postcards. He owned a luxurious hotel on the Riviera. His father and two grandfathers had sold wine, jewels and silk, respectively. At thirty he married an English girl, daughter of Jerome Dunn, the alpinist, and granddaughter of two Dorset parsons, experts in obscure subjects--paleopedology and Aeolian harps, respectively. My very photogenic mother died in a freak accident (picnic, lightning) when I was three, and, save for a pocket of warmth in the darkest past, nothing of her subsists within the hollows and dells of memory, over which, if you can still stand my style (I am writing under observation), the sun of my infancy had set: surely, you all know those redolent remnants of day suspended, with the midges, about some hedge in bloom or suddenly entered and traversed by the rambler, at the bottom of a hill, in the summer dusk; a furry warmth, golden midges.

My mother's elder sister, Sybil, whom a cousin of my father's had married and then neglected, served in my immediate family as a kind of unpaid governess and housekeeper. Somebody told me later that she had been in love with my father, and that he had lightheartedly taken advantage of it one rainy day and forgotten it by the time the weather cleared. I was extremely fond of her, despite the rigidity--the fatal rigidity--of some of her rules. Perhaps she wanted to make of me, in the fullness of time, a better widower than my father. Aunt Sybil had pink-rimmed azure eyes and a waxen complexion. She wrote poetry. She was poetically superstitious. She said she knew she would die soon after my sixteenth birthday, and did. Her husband, a great traveler in perfumes, spent most of his time in America, where eventually he founded a firm and acquired a bit of real estate.

I grew, a happy, healthy child in a bright world of illustrated books, clean sand, orange trees, friendly dogs, sea vistas and smiling faces. Around me the splendid Hotel Mirana revolved as a kind of private universe, a whitewashed cosmos within the blue greater one that blazed outside. From the aproned pot-scrubber to the flanneled potentate, everybody liked me, everybody petted me. Elderly American ladies leaning on their canes listed toward me like towers of Pisa. Ruined Russian princesses who could not pay my father, bought me expensive bonbons. He, mon cher petit papa, took me out boating and biking, taught me to swim and dive and water-ski, read to me Don Quixote and Les MisŽrables, and I adored and respected him and felt glad for him whenever I overheard the servants discuss his various lady-friends, beautiful and kind beings who made much of me and cooed and shed precious tears over my cheerful motherlessness.

I attended an English day school a few miles from home, and there I played rackets and fives, and got excellent marks, and was on perfect terms with schoolmates and teachers alike. The only definite sexual events that I can remember as having occurred before my thirteenth birthday (that is, before I first saw my little Annabel) were: a solemn, decorous and purely theoretical talk about pubertal surprises in the rose garden of the school with an American kid, the son of a then celebrated motion-picture actress whom he seldom saw in the three-dimensional world; and some interesting reactions on the part of my organism to certain photographs, pearl and umbra, with infinitely soft partings, in Pichon's sumptuous La BeautŽ Humaine that I had filched from under a mountain of marble-bound Graphics in the hotel library. Later, in his delightful debonair manner, my father gave me all the information he thought I needed about sex; this was just before sending me, in the autumn of 1923, to a lycŽe in Lyon (where we were to spend three winters); but alas, in the summer of that year, he was touring Italy with Mme. de R. and her daughter, and I had nobody to complain to, nobody to consult.

Annabel was, like the writer, of mixed parentage: half-English, half-Dutch, in her case. I remember her features far less distinctly today than I did a few years ago, before I knew Lolita. There are two kinds of visual memory: one when you skillfully recreate an image in the laboratory of your mind, with your eyes open (and then I see Annabel in such general terms as: "honey-colored skin," "thin arms," "brown bobbed hair," "long lashes," "big bright mouth"); and the other when you instantly evoke, with shut eyes, on the dark innerside of your eyelids, the objective, absolutely optical replica of a beloved face, a little ghost in natural colors (and this is how I see Lolita).

Let me therefore primly limit myself, in describing Annabel, to saying she was a lovely child a few months my junior. Her parents were old friends of my aunt's, and as stuffy as she. They had rented a villa not far from Hotel Mirana. Bald brown Mr. Leigh and fat, powdered Mrs. Leigh (born Vanessa van Ness). How I loathed them! At first, Annabel and I talked of peripheral affairs. She kept lifting handfuls of fine sand and letting it pour through her fingers. Our brains were turned the way those of intelligent European preadolescents were in our day and set, and I doubt if much individual genius should be assigned to our interest in the plurality of inhabited worlds, competitive tennis, infinity, solipsism and so on. The softness and fragility of baby animals caused us the same intense pain. She wanted to be a nurse in some famished Asiatic country; I wanted to be a famous spy.

All at once we were madly, clumsily, shamelessly, agonizingly in love with each other; hopelessly, I should add, because that frenzy of mutual possession might have been assuaged only by our actually imbibing and assimilating every particle of each other's soul and flesh; but there we were, unable even to mate as slum children would have so easily found an opportunity to do. After one wild attempt we made to meet at night in her garden (of which more later), the only privacy we were allowed was to be out of earshot but not out of sight on the populous part of the plage. There, on the soft sand, a few feet away from our elders, we would sprawl all morning, in a petrified paroxysm of desire, and take advantage of every blessed quirk in space and time to touch each other: her hand, half-hidden in the sand, would creep toward me, its slender brown fingers sleepwalking nearer and nearer; then, her opalescent knee would start on a long cautious journey; sometimes a chance rampart built by younger children granted us sufficient concealment to graze each other's salty lips; these incomplete contacts drove our healthy and inexperienced young bodies to such a state of exasperation that not even the cold blue water, under which we still clawed at each other, could bring relief.

Among some treasures I lost during the wanderings of my adult years, there was a snapshot taken by my aunt which showed Annabel, her parents and the staid, elderly, lame gentleman, a Dr. Cooper, who that same summer courted my aunt, grouped around a table in a sidewalk cafŽ. Annabel did not come out well, caught as she was in the act of bending over her chocolate glacŽ and her thin bare shoulders and the parting in her hair were about all that could be identified (as I remember that picture) amid the sunny blur into which her lost loveliness graded; but I, sitting somewhat apart from the rest, came out with a kind of dramatic conspicuousness: a moody, beetle-browed boy in a dark sport shirt and well-tailored white shorts, his legs crossed, sitting in profile, looking away. That photograph was taken on the last day of our fatal summer and just a few minutes before we made our second and final attempt to thwart fate. Under the flimsiest of pretexts (this was our very last chance, and nothing really mattered) we escaped from the cafe to the beach, and found a desolate stretch of sand, and there, in the violet shadow of some red rocks forming a kind of cave, had a brief session of avid caresses, with somebody's lost pair of sun-glasses for only witness. I was on my knees, and on the point of possessing my darling, when two bearded bathers, the old man of the sea and his brother, came out of the sea with exclamations of ribald encouragement, and four months later she died of typhus in Corfu.

I leaf again and again through these miserable memories, and keep asking myself, was it then, in the glitter of that remote summer, that the rift in my life began; or was my excessive desire for that child only the first evidence of an inherent singularity? When I try to analyze my own cravings, motives, actions and so forth, I surrender to a sort of retrospective imagination which feeds the analytic faculty with boundless alternatives and which causes each visualized route to fork and re-fork without end in the maddeningly complex prospect of my past. I am convinced, however, that in a certain magic and fateful way Lolita began with Annabel.

I also know that the shock of Annabel's death consolidated the frustration of that nightmare summer, made of it a permanent obstacle to any further romance throughout the cold years of my youth. The spiritual and the physical had been blended in us with a perfection that must remain incomprehensible to the matter-of-fact, crude, standard-brained youngsters of today. Long after her death I felt her thoughts floating through mine. Long before we met we had had the same dreams. We compared notes. We found strange affinities. The same June of the same year (1919) a stray canary had fluttered into her house and mine, in two widely separated countries. Oh, Lolita, had you loved me thus!

I have reserved for the conclusion of my "Annabel" phase the account of our unsuccessful first tryst. One night, she managed to deceive the vicious vigilance of her family. In a nervous and slender-leaved mimosa grove at the back of their villa we found a perch on the ruins of a low stone wall. Through the darkness and the tender trees we could see the arabesques of lighted windows which, touched up by the colored inks of sensitive memory, appear to me now like playing cards--presumably because a bridge game was keeping the enemy busy. She trembled and twitched as I kissed the corner of her parted lips and the hot lobe of her ear. A cluster of stars palely glowed above us, between the silhouettes of long thin leaves; that vibrant sky seemed as naked as she was under her light frock. I saw her face in the sky, strangely distinct, as if it emitted a faint radiance of its own. Her legs, her lovely live legs, were not too close together, and when my hand located what it sought, a dreamy and eerie expression, half-pleasure, half-pain, came over those childish features. She sat a little higher than I, and whenever in her solitary ecstasy she was led to kiss me, her head would bend with a sleepy, soft, drooping movement that was almost woeful, and her bare knees caught and compressed my wrist, and slackened again; and her quivering mouth, distorted by the acridity of some mysterious potion, with a sibilant intake of breath came near to my face. She would try to relieve the pain of love by first roughly rubbing her dry lips against mine; then my darling would draw away with a nervous toss of her hair, and then again come darkly near and let me feed on her open mouth, while with a generosity that was ready to offer her everything, my heart, my throat, my entrails, I gave her to hold in her awkward fist the scepter of my passion.
EOD;

return $var;
?>